name: ktor-template

services:
  proxy:
    image: traefik:v3.1.2
    command: --providers.docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  gradle-init:
    image: busybox:latest
    volumes:
      - gradle-data:/gradle-home
      - gradle-project-cache:/gradle-project-cache
    command: sh -c "mkdir -p /gradle-home /gradle-project-cache && chown -R 1000:1000 /gradle-home /gradle-project-cache"
    restart: "no"

  app:
    image: eclipse-temurin:21-jdk
    labels:
      traefik.http.routers.client.rule: "Host(`ktor-template.localhost`)"
      traefik.http.services.client.loadbalancer.server.port: "8080"
    volumes:
      - ./../../:/app
      - gradle-data:/gradle-home
      - gradle-project-cache:/gradle-project-cache
    working_dir: /app
    user: "1000:1000"
    ports:
      - "5005:5005"
      - "8080:8080"
    environment:
      APP_ENV: "DEVELOPMENT"
      GRADLE_USER_HOME: "/gradle-home"
    depends_on:
      - proxy
      - gradle-init
    command: ./gradlew run --no-daemon --project-cache-dir /gradle-project-cache
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://0.0.0.0:8080/health || exit 1" ]
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 60s

volumes:
  gradle-data:
  gradle-project-cache:
