name: ktor-template

services:
  proxy:
    image: traefik:v3.1.2
    command: --providers.docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    build: .
    labels:
      traefik.http.routers.client.rule: "Host(`ktor-template.localhost`)"
      traefik.http.services.client.loadbalancer.server.port: "8080"
    volumes:
      - ./../../:/app
      - gradle-data:/gradle-home
      - gradle-project-cache:/project-cache
    working_dir: /app
    user: "1000:1000"
    ports:
      - "5005:5005"
      - "8080:8080"
    environment:
      APP_ENV: "DEVELOPMENT"
      GRADLE_USER_HOME: "/gradle-home"
    depends_on:
      - proxy
    command: ./gradlew run --no-daemon --project-cache-dir /project-cache

volumes:
  gradle-data:
  gradle-project-cache:
